version: "3"

services:
  db:
    container_name: platform-ama-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - 1433:${DB_PORT}
